### ISSUE TITLE
两个bug

### ISSUE THREAD

**Issue by Ryziii** [Project-Gutenberg/Pincong#1]
1. 微博谈没有图
2. 点进微博谈的地址也无法进入正确地址

![](https://i.imgur.com/dMludc0.jpg)

![](https://i.imgur.com/d9ZPxTv.jpg)

**Comment by speechfree** [comment]
你好，谢谢反馈，烦请把相关的链接复制于此以便修复，谢谢！

**Comment by Ryziii** [comment]
rss订阅中出现的微博谈文章：https://project-gutenberg.github.io/Pincong/post/2139104f5f5ecf373d1cff2f6a768530/
文中出现的打不开的地址：
1. https://botanwang.com/articles/202111/%E3%80%96%E5%BE%AE%E5%8D%9A%E8%B0%88%E3%80%97%E4%B8%AD%E5%85%B1%E5%BF%A7%E2%80%9C%E7%AB%8B%E9%99%B6%E5%AE%9B%E6%A8%A1%E5%BC%8F%E2%80%9D.html](
2. https://botanwang.com/articles/202111/%E3%80%96%E5%BE%AE%E5%8D%9A%E8%B0%88%E3%80%97%E4%B8%AD%E5%85%B1%E5%BF%A7%E2%80%9C%E7%AB%8B%E9%99%B6%E5%AE%9B%E6%A8%A1%E5%BC%8F%E2%80%9D.html%22

**Comment by speechfree** [comment]
@Ryziii 谢谢反馈，已修复，请明后两天再行确认
